#!/usr/bin/env bash

function _fogg_api_gateway_profile {
  local shome="${_fogg_api_gateway_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  #export ANSIBLE_ROLES_PATH="$shome/roles${ANSIBLE_ROLES_PATH:+:${ANSIBLE_ROLES_PATH}}"
  #export ANSIBLE_LIBRARY="$shome/library${ANSIBLE_LIBRARY:+:${ANSIBLE_LIBRARY}}"

  FOGG_API_GATEWAY_VERSION='0.0.1'
}

_fogg_api_gateway_profile
