#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_api_gateway="0.0.1"
  jq -n --arg fogg_api_gateway "$ver_fogg_api_gateway" '{fogg_api_gateway: $fogg_api_gateway}'
}

version "$@"
